# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Mathias Brandewinder blog'
tagline:          'Figuring things out, one model at a time.'
description:      'Mathias Brandewinder blog, mainly about software development and numeric analysis'
url:              https://mathias-brandewinder.github.io/
baseurl:          https://mathias-brandewinder.github.io/

author:
  name:           'Mathias Brandewinder'
  url:            https://twitter.com/brandewinder

paginate:         5
excerpt_separator: <!--more-->

# Custom vars
version:          3.9.2

github:
  repo:           https://github.com/mathias-brandewinder/mathias-brandewinder.github.io/

plugins:
  - jekyll-feed