# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            ''
tagline:          'Mathias Brandewinder blog'
description:      'Figuring things out, one model at a time.'
url:              https://mathias-brandewinder.github.io/
baseurl:          https://mathias-brandewinder.github.io/

author:
  name:           'Mathias Brandewinder'
  url:            https://twitter.com/brandewinder

paginate:         5
excerpt_separator: <!--more-->

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mathias-brandewinder/mathias-brandewinder.github.io/
